export const content = {
  en: {
    heroTag: "The Gold Standard of Brokerage",
    heroTitle: "Redefining the",
    heroSkyline: "Skyline",
    heroOfTrust: "of Trust.",
    heroPara: "Homoget Properties is more than a brokerage; we are the architects of your future in the world's most dynamic real estate market.",
    yearsLabel: "Years of Excellence",
    assetsLabel: "Assets Managed",
    
    narrativeTitle: "Our Narrative",
    narrativePara: "Founded in the heart of Dubai, Homoget Properties L.L.C. S.O.C. was born from a singular vision: to bridge the gap between global investors and the UAE's most exclusive opportunities. As a fully licensed and RERA-regulated firm, we bring transparency, integrity, and human-centric innovation to every transaction.",
    narrativeBtn: "Discover Our Mission",
    
    strategyTitle: "Precision Brokerage",
    strategyPara: "We leverage proprietary market analytics and AI-enhanced search capabilities to predict market cycles, ensuring our clients enter the market at the peak of opportunity while minimizing risk.",
    
    meaningTitle: "Understanding 'HomoGet'",
    meaningPara: "HomoGet is a human-centric concept that represents the acquisition of any object, service, information, or assistance—either directly from one human to another or through technology, platforms, or resources created by humans. Word breakdown: Homo (Human) + Get (to obtain/acquire). Core meaning: acquisition by humans, or obtaining from humans. Professional definition: the process through which an individual acquires any object, service, knowledge, or support – directly from another person or indirectly via tools, platforms, or systems developed by humans. One‑line definition: 'HomoGet is a human‑centric mode of acquisition in which the original source of every resource is, directly or indirectly, human.'",
    
    visionTitle: "Our Vision",
    visionPara: "To build an all-in-one, inclusive digital platform that empowers individuals, small businesses, and entrepreneurs across diverse sectors. We aspire to create a comprehensive ecosystem including real estate listing, online promotions, e‑commerce, secure payments, banking, currency exchange, online pharmacy, ticket bookings – all integrated under one intuitive platform. Core promise: charge the lowest possible fees, enabling even the smallest entrepreneurs to advertise, sell, and scale without financial barriers.",
    
    legalTitle: "Legal & License Details",
    legalName: "Homoget Properties L.L.C. S.O.C.",
    legalDesc: "Fully licensed and registered Limited Liability Company – Single Owner (LLC – S.O.C.) in Dubai, UAE. Issued by DET and regulated by RERA.",
    licenseNo: "License: 1523268",
    reraNo: "RERA ORN: 52933",
    office: "R-118, 2nd Floor, Wasl Building, Makani No. 2809195296, Bur Dubai, Dubai, United Arab Emirates",
    ownerLabel: "Ownership",
    ownerName: "Founded & Solely Owned by Prashant Singh",
    capital: "AED 300,000",
    incorporationDate: "July 17, 2025",
    permittedActivities: "Leasing Property Brokerage Agents | Real Estate Buying & Selling Brokerage",
    
    foundersTitle: "The Visionaries Behind HomoGet",
    foundersSub: "Meet the leaders shaping Dubai's real estate future",
    founderName: "Prashant Singh",
    founderRole: "Founder & CEO",
    founderimage: "https://media.istockphoto.com/id/1406880505/photo/portrait-of-businessman-sitting-in-office-successful-man-worker-employee-by-work-desk-looking.jpg?s=612x612&w=0&k=20&c=iwRLj4ZpAth5vIar-BcY5kEG-i9sO8kGOgFwm3kIp4g=",
    founderDesc: "A visionary entrepreneur with over 12+ years of experience in Dubai's luxury real estate market. Prashant Singh founded HomoGet with a mission to democratize property acquisition and bring transparency to the UAE real estate sector. Under his leadership, HomoGet has grown into a trusted brokerage firm managing over AED 5B+ in assets. His deep understanding of market dynamics and commitment to client success has made HomoGet a benchmark for excellence in Dubai's competitive property landscape.",
    founderAchievements: ["12+ Years Experience", "AED 5B+ Assets Managed", "RERA Certified", "Industry Pioneer"],
    
    coFounderName: "Anjali Singh",
    coFounderRole: "Co-Founder & Managing Director",
    coFounderimage: "https://media.istockphoto.com/id/470745398/photo/young-emirati-businesswoman-looking-away-at-conference-table.jpg?s=612x612&w=0&k=20&c=tlP-4VDc-rOC1q5QEcGLOsUA4Apgg_U0DmKoLqwpvZw=",
    coFounderDesc: "Anjali Singh brings a unique blend of operational excellence and customer-centric innovation to HomoGet. With a background in international business and client relations, she has been instrumental in building HomoGet's reputation for white-glove service. Anjali oversees the company's strategic partnerships, compliance framework, and client experience initiatives. Her dedication to ethical brokerage practices has earned HomoGet the trust of investors from over 30 countries worldwide.",
    coFounderAchievements: ["Operations Expert", "Client Relations Specialist", "Global Partnership Leader", "Compliance Champion"],
    
    faqTitle: "Knowledge Base",
    faqSub: "Frequently Asked Questions",
    faqs: [
      { q: "What types of properties does HOMOGET handle?", a: "HOMOGET deals with residential (apartments, villas, townhouses), commercial properties, and off-plan/investment projects across Dubai." },
      { q: "Is HOMOGET licensed and regulated in Dubai?", a: "Yes — HOMOGET is fully licensed under the Dubai Land Department (DLD) with License No. 1523268, and our agents hold valid RERA certifications (ORN 52933)." },
      { q: "How can I verify HOMOGET’s credentials?", a: "You can check our licence number and our agents’ RERA IDs via the Dubai REST app or the official DLD website." },
      { q: "Can non-UAE residents buy property in Dubai?", a: "Yes. Foreign nationals can purchase freehold property in designated areas of Dubai. HOMOGET assists international investors with the entire legal process." },
      { q: "What costs are involved when buying a property?", a: "Costs typically include DLD registration fee (4%), Admin fees, Agent commission (2%), and service charges." },
      { q: "What is an off-plan property purchase?", a: "Off-plan means buying a property before it is built. Payments are made in stages based on construction progress." },
      { q: "What is an escrow account?", a: "It's a secure account that holds the buyer's payments until the developer meets construction milestones, protecting your investment by law in Dubai." },
      { q: "What is Ejari?", a: "Ejari is Dubai's official tenancy registration system, required for all rental agreements." },
      { q: "Can I rent without visiting Dubai?", a: "Yes — we offer virtual tours and verified digital contracts to ensure a safe rental process from anywhere." },
      { q: "What is the difference between freehold and leasehold?", a: "Freehold gives full ownership (forever), while leasehold provides rights for a fixed term (e.g., 99 years)." }
    ]
  },
  
  hi: {
    heroTag: "ब्रोकरेज का स्वर्ण मानक",
    heroTitle: "विश्वास की",
    heroSkyline: "ऊंचाइयों",
    heroOfTrust: "को नया रूप देना।",
    heroPara: "होमोगेट प्रॉपर्टीज सिर्फ एक ब्रोकरेज नहीं है; हम दुनिया के सबसे गतिशील रियल एस्टेट बाजार में आपके भविष्य के वास्तुकार हैं।",
    yearsLabel: "उत्कृष्टता के वर्ष",
    assetsLabel: "संपत्ति प्रबंधन",
    narrativeTitle: "हमारी कहानी",
    narrativePara: "दुबई के केंद्र में स्थापित, होमोगेट प्रॉपर्टीज एल.एल.सी. एस.ओ.सी. एक दृष्टिकोण के साथ पैदा हुआ: वैश्विक निवेशकों और यूएई के सबसे विशेष अवसरों के बीच की दूरी को पाटना।",
    narrativeBtn: "हमारे मिशन को जानें",
    strategyTitle: "सटीक ब्रोकरेज",
    strategyPara: "हम चक्रों की भविष्यवाणी करने के लिए मालिकाना बाजार विश्लेषण का लाभ उठाते हैं।",
    meaningTitle: "होमोगेट क्या है?",
    meaningPara: "होमोगेट अधिग्रहण का एक मानव-केंद्रित तरीका है जिसमें प्रत्येक संसाधन का मूल स्रोत प्रत्यक्ष या अप्रत्यक्ष रूप से मानव होता है। (पूर्ण परिभाषा के लिए अंग्रेजी संस्करण देखें)",
    visionTitle: "हमारा दृष्टिकोण",
    visionPara: "एक समावेशी डिजिटल प्लेटफॉर्म बनाना जो व्यक्तियों और छोटे व्यवसायों को सशक्त बनाए।",
    legalTitle: "कानूनी और लाइसेंस विवरण",
    legalName: "होमोगेट प्रॉपर्टीज एल.एल.सी. एस.ओ.सी.",
    legalDesc: "दुबई, यूएई में पूरी तरह से लाइसेंस प्राप्त और पंजीकृत लिमिटेड लायबिलिटी कंपनी – एकल स्वामित्व। DET द्वारा जारी और RERA द्वारा विनियमित।",
    licenseNo: "लाइसेंस: 1523268",
    reraNo: "RERA: 52933",
    office: "आर-118, दूसरी मंजिल, वास्ल बिल्डिंग, मकानी नं. 2809195296, बुर दुबई, दुबई, यूएई",
    ownerLabel: "स्वामित्व",
    ownerName: "प्रशांत सिंह द्वारा स्थापित और एकमात्र स्वामित्व",
    foundersTitle: "होमोगेट के पीछे दूरदर्शी",
    foundersSub: "दुबई के रियल एस्टेट भविष्य को आकार देने वाले नेताओं से मिलें",
    founderName: "प्रशांत सिंह",
    founderRole: "संस्थापक और सीईओ",
    founderimage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-1.2.1&auto=format&fit=crop&w=870&q=80",
    founderDesc: "दुबई के लग्जरी रियल एस्टेट बाजार में 12+ वर्षों के अनुभव वाले एक दूरदर्शी उद्यमी।",
    founderAchievements: ["12+ वर्ष अनुभव", "AED 5B+ संपत्ति", "RERA प्रमाणित", "उद्योग अग्रणी"],
    coFounderName: "अंजलि सिंह",
    coFounderRole: "सह-संस्थापक और प्रबंध निदेशक",
    coFounderimage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-1.2.1&auto=format&fit=crop&w=870&q=80",
    coFounderDesc: "अंजलि सिंह होमोगेट में परिचालन उत्कृष्टता और ग्राहक-केंद्रित नवाचार लाती हैं।",
    coFounderAchievements: ["संचालन विशेषज्ञ", "ग्राहक संबंध विशेषज्ञ", "वैश्विक साझेदारी नेता", "अनुपालन चैंपियन"],
    faqTitle: "सामान्य प्रश्न",
    faqSub: "अक्सर पूछे जाने वाले सवाल",
    faqs: [
      { q: "होमोगेट किस प्रकार की संपत्तियों का प्रबंधन करता है?", a: "होमोगेट पूरे दुबई में आवासीय (अपार्टमेंट, विला, टाउनहाउस), वाणिज्यिक संपत्तियों और ऑफ-प्लान परियोजनाओं का प्रबंधन करता है।" },
      { q: "क्या होमोगेट दुबई में लाइसेंस प्राप्त है?", a: "हाँ - होमोगेट दुबई भूमि विभाग (DLD) के तहत पूरी तरह से लाइसेंस प्राप्त है।" }
    ]
  },
  
  ar: {
    heroTag: "المعيار الذهبي للوساطة",
    heroTitle: "إعادة تعريف",
    heroSkyline: "أفق",
    heroOfTrust: "الثقة.",
    heroPara: "هوموجيت بروبرتيز هي أكثر من مجرد شركة وساطة؛ نحن مهندسو مستقبلك في سوق العقارات الأكثر ديناميكية في العالم.",
    yearsLabel: "سنوات من التميز",
    assetsLabel: "أصول تحت الإدارة",
    narrativeTitle: "سردنا",
    narrativePara: "تأسست هوموجيت بروبرتيز ش.ذ.م.م - مالك واحد في قلب دبي، ولدت من رؤية فريدة: سد الفجوة بين المستثمرين العالميين وأكثر الفرص حصرياً في الإمارات.",
    narrativeBtn: "اكتشف مهمتنا",
    strategyTitle: "وساطة دقيقة",
    strategyPara: "نحن نستخدم تحليلات السوق للتنبؤ بالدورات العقارية، مما يضمن دخول عملائنا السوق في ذروة الفرص.",
    meaningTitle: "ما هو هوموجيت؟",
    meaningPara: "هوموجيت هو نمط اقتناء يركز على الإنسان، حيث يكون المصدر الأصلي لكل مورد هو الإنسان بشكل مباشر أو غير مباشر. (للاطلاع على التعريف الكامل، راجع النسخة الإنجليزية)",
    visionTitle: "رؤيتنا",
    visionPara: "بناء منصة رقمية شاملة تمكن الأفراد والشركات الصغيرة ورواد الأعمال في مختلف القطاعات.",
    legalTitle: "تفاصيل الترخيص القانوني",
    legalName: "هوموجيت بروبرتيز ش.ذ.م.م - مالك واحد",
    legalDesc: "شركة ذات مسؤولية محدودة مرخصة ومسجلة بالكامل في دبي، الإمارات العربية المتحدة. صادرة عن DET ومنظمة من قبل ريرا.",
    licenseNo: "رخصة: 1523268",
    reraNo: "ريرا: 52933",
    office: "R-118، الطابق الثاني، مبنى وصل، رقم مكاني 2809195296، بر دبي، دبي",
    ownerLabel: "الملكية",
    ownerName: "تأسست ومملوكة بالكامل من قبل براشانت سينغ",
    foundersTitle: "الرؤى وراء هوموجيت",
    foundersSub: "تعرف على القادة الذين يشكلون مستقبل العقارات في دبي",
    founderName: "براشانت سينغ",
    founderRole: "المؤسس والرئيس التنفيذي",
    founderimage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-1.2.1&auto=format&fit=crop&w=870&q=80",
    founderDesc: "رائد أعمال ذو رؤية يتمتع بخبرة تزيد عن 12 عامًا في سوق العقارات الفاخرة في دبي.",
    founderAchievements: ["خبرة 12+ سنة", "إدارة أصول بقيمة 5+ مليار درهم", "معتمد من ريرا", "رائد في المجال"],
    coFounderName: "انجالي سينغ",
    coFounderRole: "المؤسس المشارك والمدير العام",
    coFounderimage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-1.2.1&auto=format&fit=crop&w=870&q=80",
    coFounderDesc: "تجلب انجالي سينغ مزيجًا فريدًا من التميز التشغيلي والابتكار المرتكز على العملاء إلى هوموجيت.",
    coFounderAchievements: ["خبيرة عمليات", "أخصائية علاقات عملاء", "قائدة شراكات عالمية", "بطلة الامتثال"],
    faqTitle: "الأسئلة الشائعة",
    faqSub: "قاعدة المعرفة",
    faqs: [
      { q: "ما هي أنواع العقارات التي تتعامل معها هوموجيت؟", a: "تتعامل هوموجيت مع العقارات السكنية والتجارية والمشاريع قيد الإنشاء في جميع أنحاء دبي." },
      { q: "هل هوموجيت مرخصة ومنظمة في دبي؟", a: "نعم — هوموجيت مرخصة بالكامل من قبل دائرة الأراضي والأملاك في دبي (DLD) ولدى وكلائها شهادات ريرا." }
    ]
  }
};