export const UAE_STATES = ["Dubai", "Abu Dhabi", "Sharjah", "Ajman", "Ras Al Khaimah", "Fujairah", "Umm Al Quwain"];

export const DUBAI_AREAS = [
  "Palm Jumeirah", "Dubai Marina", "Downtown Dubai", "Business Bay", 
  "Jumeirah Village Circle (JVC)", "Jumeirah Lakes Towers (JLT)", 
  "Dubai Hills Estate", "Arabian Ranches", "DAMAC Hills", "Dubai Creek Harbour",
  "Emaar Beachfront", "Meydan", "MBR City", "Al Furjan", "Dubai South", 
  "Bluewaters Island", "City Walk", "Jumeirah Golf Estates", "Arjan"
].sort();

export const PROPERTY_TYPES = [
  // --- Residential ---
  "Apartment", 
  "Villa", 
  "Townhouse", 
  "Penthouse", 
  "Hotel Apartment",
  "Compound",
  "Duplex",
  "Full Floor Residential",
  
  // --- Commercial ---
  "Office", 
  "Retail", 
  "Warehouse", 
  "Full Building",
  "Showroom",
  "Industrial Land",
  "Labor Camp",
  
  // --- Land & Specialized ---
  "Land", 
  "Residential Plot",
  "Commercial Plot",
  "Mixed Use Plot"
];

export const AMENITIES = [
  "Infinity Pool",
  "Private Pool",
  "Shared Pool",
  "Kids Pool",
  "Jacuzzi",
  "Spa",
  "Sauna",
  "Steam Room",
  "Shared Gym",
  "Private Gym",
  "Yoga Studio",
  "Fitness Center",
  "Sports Court",
  "Tennis Court",
  "Basketball Court",
  "Squash Court",
  "Jogging Track",
  "Cycling Track",
  "Golf Course",
  "Mini Golf",
  "Beach Access",
  "Private Beach",
  "Lagoon View",
  "Waterfront",
  "Marina View",
  "Sea View",
  "Canal View",
  "Park View",
  "Burj Khalifa View",
  "Palm Jumeirah View",
  "Skyline View",
  "Balcony",
  "Private Garden",
  "Rooftop Terrace",
  "Terrace",
  "BBQ Area",
  "Outdoor Dining Area",
  "Outdoor Lounge",
  "Children's Play Area",
  "Kids Club",
  "Day Care Center",
  "Community Center",
  "Clubhouse",
  "Multipurpose Hall",
  "Cinema Room",
  "Game Room",
  "Library",
  "Business Center",
  "Coworking Space",
  "Conference Room",
  "Prayer Room",
  "Retail Shops",
  "Shopping Mall Nearby",
  "Restaurants Nearby",
  "Cafes Nearby",
  "Supermarket Nearby",
  "Pharmacy Nearby",
  "School Nearby",
  "Hospital Nearby",
  "Public Transport",
  "Metro Access",
  "Concierge Service",
  "Reception Service",
  "Valet Parking",
  "Visitor Parking",
  "Covered Parking",
  "Basement Parking",
  "Private Garage",
  "EV Charging Station",
  "Smart Home System",
  "Central Air Conditioning",
  "Central Heating",
  "High-Speed Elevators",
  "Service Elevators",
  "Maid Service",
  "Maid Room",
  "Driver Room",
  "Laundry Room",
  "Storage Room",
  "Walk-in Closet",
  "Built-in Wardrobes",
  "Fully Furnished",
  "Semi Furnished",
  "Kitchen Appliances",
  "Study Room",
  "Office Room",
  "Private Office",
  "24/7 Security",
  "CCTV Security",
  "Gated Community",
  "Access Control",
  "Intercom",
  "Fire Safety System",
  "Backup Power",
  "Pet Friendly",
  "Pets Allowed",
  "Wheelchair Accessible",
  "Disabled Access",
  "Green Building",
  "Solar Panels",
  "Energy Efficient",
  "Housekeeping",
  "Cleaning Service",
  "Chauffeur Service",
  "Shuttle Service",
  "Airport Transfer",
  "Private Entrance",
  "Luxury Lobby",
  "High Floor",
  "Corner Unit",
  "Vastu Compliant",
  "Near Metro",
  "Near Mall",
  "Near Beach",
  "Near Airport",
  "Near Downtown",
  "Ready to Move",
  "Off Plan",
  "Fitted Kitchen",
  "Open Kitchen",
  "Closed Kitchen",
  "Duplex",
  "Penthouse",
  "Serviced Apartment"
];






